#!/usr/bin/env python3
"""
Generate the dwmapi proxy export files from an `.exports` file (into ../src):
  proxy_exports.def   - linker export table  (name=f<i> @<ord>)
  proxy_exports.asm   - MASM jump stubs       (f<i>: jmp mProcs[8*i])
  proxy_generated.inc - mProcs[] + setup_functions()
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))


def read_exports(path):
    """Replicates ReadExportsFile(): first 'Path: ' line, then '<ordinal> [name]'."""
    exports = []  # list of (ordinal:int, is_named:bool, name:str)
    with open(path, "r", encoding="utf-8") as f:
        first = f.readline()
        if "Path: " not in first:
            print("Failed to read export file (missing file path info)", file=sys.stderr)
            sys.exit(1)
        for line in f:
            parts = line.split()
            if not parts:
                continue
            try:
                ordinal = int(parts[0])
            except ValueError:
                continue
            if ordinal == 0:  # invalid line
                continue
            name = parts[1] if len(parts) > 1 else ""
            is_named = bool(name)
            exports.append((ordinal, is_named, name if is_named else f"ordinal{ordinal}"))
    return exports


def write_def(exports, lib="dwmapi"):
    lines = [f"LIBRARY {lib}", "EXPORTS"]
    for i, (ordinal, _is_named, name) in enumerate(exports):
        lines.append(f"  {name}=f{i} @{ordinal}")
    _write(os.path.join(SRC, "proxy_exports.def"), "\n".join(lines) + "\n")


def write_asm(exports):
    lines = [".code", "extern mProcs:QWORD"]
    for i in range(len(exports)):
        lines.append(f"f{i} proc")
        lines.append(f"  jmp mProcs[8*{i}]")
        lines.append(f"f{i} endp")
    lines.append("end")
    _write(os.path.join(SRC, "proxy_exports.asm"), "\n".join(lines) + "\n")


def write_inc(exports):
    n = len(exports)
    lines = [
        "// AUTO-GENERATED by tools/gen_proxy.py from tools/dwmapi.exports - do not edit.",
        f'extern "C" uintptr_t mProcs[{n}] = {{0}};',
        "",
        "static void setup_functions()",
        "{",
    ]
    for i, (ordinal, is_named, name) in enumerate(exports):
        getter = f'"{name}"' if is_named else f"MAKEINTRESOURCEA({ordinal})"
        lines.append(f"    mProcs[{i}] = (uintptr_t)GetProcAddress(SOriginalDll, {getter});")
    lines.append("}")
    _write(os.path.join(SRC, "proxy_generated.inc"), "\n".join(lines) + "\n")


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {path}")


def main():
    exp_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "dwmapi.exports")
    exports = read_exports(exp_path)
    print(f"export count: {len(exports)}")
    write_def(exports)
    write_asm(exports)
    write_inc(exports)
    print("done")


if __name__ == "__main__":
    main()
